# Generated by Django 5.1.5 on 2025-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_description_course_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="update_time",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="upload_time",
            field=models.DateField(auto_now_add=True),
        ),
    ]
