# Generated by Django 5.1.5 on 2025-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
