# Generated by Django 5.1.5 on 2025-01-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_upload_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="update_time",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="upload_time",
            field=models.DateField(auto_now_add=True),
        ),
    ]
