# Generated by Django 5.1.5 on 2025-01-30 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_rename_yt_id_lesson_video_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="upload_time",
        ),
    ]
