# Generated by Django 5.1.5 on 2025-02-01 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_lesson_duration_alter_lesson_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="author",
        ),
    ]
