# Generated by Django 5.1.5 on 2025-02-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_category_parent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
