# Generated by Django 5.1.5 on 2025-02-02 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_lesson_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 0, 19, 2, 459836)),
        ),
        migrations.AddField(
            model_name='course',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 0, 19, 2, 459824)),
        ),
    ]
