# Generated by Django 5.1.5 on 2025-02-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=2),
        ),
    ]
