# Generated by Django 5.1.5 on 2025-02-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0027_alter_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
